# Generated by Django 4.2.4 on 2023-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPerfil', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
