# Generated by Django 4.2.4 on 2023-09-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAndrada', '0002_delete_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
